package com.example.myapplication;

import java.util.ArrayList;

// whole point of this class is to add data into the database

public class DBData {
    ArrayList<Object> routeData = new ArrayList<>();

    public ArrayList<Object> routeInit(){
        routeData.add("62B"); routeData.add(1); routeData.add("Pit-os");
        routeData.add("62B"); routeData.add(2); routeData.add("Bacayan");
        routeData.add("62B"); routeData.add(3); routeData.add("Talamban");
        routeData.add("62B"); routeData.add(4); routeData.add("Grand Mall");
        routeData.add("62B"); routeData.add(5); routeData.add("USC Talamban");
        routeData.add("62B"); routeData.add(6); routeData.add("Country Mall");
        routeData.add("62B"); routeData.add(7); routeData.add("Ayala Center Cebu");
        routeData.add("62B"); routeData.add(8); routeData.add("Capitol");
        routeData.add("12L"); routeData.add(1); routeData.add("Labangon");
        routeData.add("12L"); routeData.add(2); routeData.add("CCNSHS");
        routeData.add("12L"); routeData.add(3); routeData.add("Gaisano Tisa");
        routeData.add("12L"); routeData.add(4); routeData.add("VSMMC");
        routeData.add("12L"); routeData.add(5); routeData.add("Fuente Osmeña");
        routeData.add("12L"); routeData.add(6); routeData.add("Mango");
        routeData.add("12L"); routeData.add(7); routeData.add("Ayala Center Cebu");
        routeData.add("12L"); routeData.add(8); routeData.add("Capitol");
        routeData.add("12L"); routeData.add(9); routeData.add("Banawa");
        routeData.add("23"); routeData.add(1); routeData.add("Parkmall");
        routeData.add("23"); routeData.add(2); routeData.add("S&R Membership Shopping");
        routeData.add("23"); routeData.add(3); routeData.add("Cebu Doctors University");
        routeData.add("23"); routeData.add(4); routeData.add("St James Amusement Park");
        routeData.add("23"); routeData.add(5); routeData.add("Mandaue City Sports and Cultural Complex");
        routeData.add("23"); routeData.add(6); routeData.add("Bureau of Internal Revenue BIR");
        routeData.add("23"); routeData.add(7); routeData.add("New Mandaue Public Market");
        routeData.add("23"); routeData.add(8); routeData.add("Mandaue City Hospital");
        routeData.add("23"); routeData.add(9); routeData.add("Norkis Park");
        routeData.add("23"); routeData.add(10); routeData.add("Mandaue City Central School");
        routeData.add("23"); routeData.add(11); routeData.add("University of Visayas");
        routeData.add("23"); routeData.add(12); routeData.add("Hotel Nenita");
        routeData.add("23"); routeData.add(13); routeData.add("Tita Gwapa");
        routeData.add("23"); routeData.add(14); routeData.add("Bridges Town Square");
        routeData.add("23"); routeData.add(15); routeData.add("Kosmos Furniture Designs Philippines Inc");
        routeData.add("23"); routeData.add(16); routeData.add("UN Ave");
        routeData.add("23"); routeData.add(17); routeData.add("Mactan Marina Mall");
        routeData.add("23"); routeData.add(18); routeData.add("Savemore");
        routeData.add("23"); routeData.add(19); routeData.add("Ibo Elementary School");
        routeData.add("23"); routeData.add(20); routeData.add("EMD Carmelite School");
        routeData.add("23"); routeData.add(21); routeData.add("American International Training Institute");
        routeData.add("23"); routeData.add(22); routeData.add("Mactan Elementary School");
        routeData.add("23"); routeData.add(23); routeData.add("Mactan Shrine");
        routeData.add("23"); routeData.add(24); routeData.add("Mares Philippines");
        routeData.add("23"); routeData.add(25); routeData.add("Movenpick Hotel Mactan Island Cebu");
        routeData.add("23"); routeData.add(26); routeData.add("AITI Native Center");
        routeData.add("23"); routeData.add(27); routeData.add("Be Resorts Mactan");
        routeData.add("23"); routeData.add(28); routeData.add("Cebu Sea World");
        routeData.add("23"); routeData.add(29); routeData.add("Punta Engano Elementary and High School");
        routeData.add("23"); routeData.add(30); routeData.add("Amisa Residences");
        routeData.add("23D"); routeData.add(1); routeData.add("Parkmall");
        routeData.add("23D"); routeData.add(2); routeData.add("S&R Membership Shopping");
        routeData.add("23D"); routeData.add(3); routeData.add("Cebu Doctors University");
        routeData.add("23D"); routeData.add(4); routeData.add("St James Amusement Park");
        routeData.add("23D"); routeData.add(5); routeData.add("Mandaue City Sports and Cultural Complex");
        routeData.add("23D"); routeData.add(6); routeData.add("Bureau of Internal Revenue BIR");
        routeData.add("23D"); routeData.add(7); routeData.add("New Mandaue Public Market");
        routeData.add("23D"); routeData.add(8); routeData.add("Mandaue City Hospital");
        routeData.add("23D"); routeData.add(9); routeData.add("Norkis Park");
        routeData.add("23D"); routeData.add(10); routeData.add("Mandaue City Central School");
        routeData.add("23D"); routeData.add(11); routeData.add("University of Visayas");
        routeData.add("23D"); routeData.add(12); routeData.add("Hotel Nenita");
        routeData.add("23D"); routeData.add(13); routeData.add("University of Cebu");
        routeData.add("23D"); routeData.add(14); routeData.add("Mantawe Road");
        routeData.add("23D"); routeData.add(15); routeData.add("Ompad St");
        routeData.add("23D"); routeData.add(16); routeData.add("La Nueva Supermarket");
        routeData.add("23D"); routeData.add(17); routeData.add("Super Metro Gaisano Lapu-Lapu");
        routeData.add("23D"); routeData.add(18); routeData.add("Lapu Lapu City PUJ Terminal");
        routeData.add("MI-01A"); routeData.add(1); routeData.add("Ompad St");
        routeData.add("MI-01A"); routeData.add(2); routeData.add("La Nueva Supermarket");
        routeData.add("MI-01A"); routeData.add(3); routeData.add("Lapu Lapu City PUJ Terminal");
        routeData.add("MI-01A"); routeData.add(4); routeData.add("PLDT");
        routeData.add("MI-01A"); routeData.add(5); routeData.add("Gaisano Mactan");
        routeData.add("MI-01A"); routeData.add(6); routeData.add("Goldberry Suites and Hotel");
        routeData.add("MI-01A"); routeData.add(7); routeData.add("Mactan Marina Mall");
        routeData.add("MI-01A"); routeData.add(8); routeData.add("Savemore");
        routeData.add("MI-01A"); routeData.add(9); routeData.add("Ibo Elementary School");
        routeData.add("MI-01A"); routeData.add(10); routeData.add("EMD Carmelite School");
        routeData.add("MI-01A"); routeData.add(11); routeData.add("Mactan Shrine");
        routeData.add("MI-01A"); routeData.add(12); routeData.add("Mares Philippines");
        routeData.add("MI-01A"); routeData.add(13); routeData.add("Movenpick Hotel Mactan Island Cebu");
        routeData.add("MI-01A"); routeData.add(14); routeData.add("AITI Native Center");
        routeData.add("MI-01A"); routeData.add(15); routeData.add("Be Resorts Mactan");
        routeData.add("MI-01A"); routeData.add(16); routeData.add("Cebu Sea World");
        routeData.add("MI-01A"); routeData.add(17); routeData.add("Punta Engano Elementary and High School");
        routeData.add("MI-01A"); routeData.add(18); routeData.add("Amisa Residences");
        routeData.add("MI-02B"); routeData.add(1); routeData.add("Imperial Palace Waterpark Resort & Spa");
        routeData.add("MI-02B"); routeData.add(2); routeData.add("Mactan Island Aquarium");
        routeData.add("MI-02B"); routeData.add(3); routeData.add("Cebu White Sands");
        routeData.add("MI-02B"); routeData.add(4); routeData.add("Maribago bluewater Beach Resort and Spa");
        routeData.add("MI-02B"); routeData.add(5); routeData.add("Mactan Oasis Garden");
        routeData.add("MI-02B"); routeData.add(6); routeData.add("Sto Nino de Mactan Church");
        routeData.add("MI-02B"); routeData.add(7); routeData.add("American Internation Training Institute");
        routeData.add("MI-02B"); routeData.add(8); routeData.add("Ibo Elementary School");
        routeData.add("MI-02B"); routeData.add(9); routeData.add("Savemore");
        routeData.add("MI-02B"); routeData.add(10); routeData.add("Mactan Marina Mall");
        routeData.add("MI-02B"); routeData.add(11); routeData.add("UN Ave");
        routeData.add("MI-02B"); routeData.add(12); routeData.add("Kosmos Furniture Designs Philippines Inc");
        routeData.add("MI-02B"); routeData.add(13); routeData.add("Bridges Town Square");
        routeData.add("MI-02B"); routeData.add(14); routeData.add("Tita Gwapa");
        routeData.add("MI-02B"); routeData.add(15); routeData.add("Hotel Nenita");
        routeData.add("MI-02B"); routeData.add(16); routeData.add("Grand Arcade Building");
        routeData.add("MI-02B"); routeData.add(17); routeData.add("Mandaue Coliseum");
        routeData.add("MI-02B"); routeData.add(18); routeData.add("STI College");
        routeData.add("MI-02B"); routeData.add(19); routeData.add("Collegio de la Immacuada Concepcion");
        routeData.add("MI-02B"); routeData.add(20); routeData.add("Hall of Justice");
        routeData.add("MI-02B"); routeData.add(21); routeData.add("Parkmall");
        routeData.add("MI-03A"); routeData.add(1); routeData.add("Cordova");
        routeData.add("MI-03A"); routeData.add(2); routeData.add("Senor San Roque Parish Church");
        routeData.add("MI-03A"); routeData.add(3); routeData.add("Cordova Academy Cooperative School");
        routeData.add("MI-03A"); routeData.add(4); routeData.add("Cordova Municipal Hall");
        routeData.add("MI-03A"); routeData.add(5); routeData.add("Quezon National Hwy");
        routeData.add("MI-03A"); routeData.add(6); routeData.add("Babang II Road");
        routeData.add("MI-03A"); routeData.add(7); routeData.add("Cattleya Gardens and Memorial Park");
        routeData.add("MI-03A"); routeData.add(8); routeData.add("Pilipog Elementary School");
        routeData.add("MI-03A"); routeData.add(9); routeData.add("Takan Public Market Park");
        routeData.add("MI-03A"); routeData.add(10); routeData.add("Sr Santo Nino Chapel");
        routeData.add("MI-03A"); routeData.add(11); routeData.add("Babag 2 Elementary School");
        routeData.add("MI-03A"); routeData.add(12); routeData.add("Mother of Perpetual Help Parish");
        routeData.add("MI-03A"); routeData.add(13); routeData.add("Babag Night High School");
        routeData.add("MI-03A"); routeData.add(14); routeData.add("Babag Elementary School");
        routeData.add("MI-03A"); routeData.add(15); routeData.add("Maria Ernestine School");
        routeData.add("MI-03A"); routeData.add(16); routeData.add("Tojong Hospital");
        routeData.add("MI-03A"); routeData.add(17); routeData.add("Lapu Lapu City Central School");
        routeData.add("MI-03A"); routeData.add(18); routeData.add("Opon Kindergarten and Bursery School");
        routeData.add("MI-03A"); routeData.add(19); routeData.add("Lapu Lapu City Public Market");
        routeData.add("MI-03B"); routeData.add(1); routeData.add("Mepz1 2nd Ave Road");
        routeData.add("MI-03B"); routeData.add(2); routeData.add("Savemore");
        routeData.add("MI-03B"); routeData.add(3); routeData.add("Mactan Marina Mall");
        routeData.add("MI-03B"); routeData.add(4); routeData.add("The Bellavista Hotel");
        routeData.add("MI-03B"); routeData.add(5); routeData.add("Gaisano Mactan");
        routeData.add("MI-03B"); routeData.add(6); routeData.add("PLDT");
        routeData.add("MI-03B"); routeData.add(7); routeData.add("Lapu Lapu City PUJ Terminal");
        routeData.add("MI-03B"); routeData.add(8); routeData.add("Super Metro Gaisano Lapu Lapu");
        routeData.add("MI-03B"); routeData.add(9); routeData.add("Mantawe Road");
        routeData.add("MI-03B"); routeData.add(10); routeData.add("BM Dimataga St");
        routeData.add("MI-03B"); routeData.add(11); routeData.add("Opon Plaza");
        routeData.add("MI-03B"); routeData.add(12); routeData.add("Our Lady of the Rule Parish Church");
        routeData.add("MI-03B"); routeData.add(13); routeData.add("Eastern Christian School");
        routeData.add("MI-03B"); routeData.add(14); routeData.add("Lapu Lapu City Central School");
        routeData.add("MI-03B"); routeData.add(15); routeData.add("Tojong Hospital");
        routeData.add("MI-03B"); routeData.add(17); routeData.add("Marie Ernestine School");
        routeData.add("MI-03B"); routeData.add(18); routeData.add("Babag Elementary School");
        routeData.add("MI-03B"); routeData.add(19); routeData.add("Babag National High School");
        routeData.add("MI-03B"); routeData.add(20); routeData.add("Babag Night High School");
        routeData.add("MI-03B"); routeData.add(21); routeData.add("Mother of Perpetual Help Parish");
        routeData.add("MI-03B"); routeData.add(22); routeData.add("Babag 2 Elementary School");
        routeData.add("MI-03B"); routeData.add(23); routeData.add("Sr Santo Nino Chapel");
        routeData.add("MI-03B"); routeData.add(24); routeData.add("Takan Public Market Park");
        routeData.add("MI-03B"); routeData.add(25); routeData.add("Pilipog Elementary School");
        routeData.add("MI-03B"); routeData.add(26); routeData.add("Cattleya Gardens and Memorial Park");
        routeData.add("MI-03B"); routeData.add(27); routeData.add("Babang II Road");
        routeData.add("MI-03B"); routeData.add(28); routeData.add("Cordova Central School");
        routeData.add("MI-03B"); routeData.add(29); routeData.add("Cordova Municipal Hall");
        routeData.add("MI-03B"); routeData.add(30); routeData.add("Cordova Academy Cooperative School");
        routeData.add("MI-03B"); routeData.add(31); routeData.add("Senor San Roque Parish Church");
        routeData.add("MI-03B"); routeData.add(32); routeData.add("Cordova");
        routeData.add("MI-04A"); routeData.add(1); routeData.add("J Centre");
        routeData.add("MI-04A"); routeData.add(2); routeData.add("Savemore");
        routeData.add("MI-04A"); routeData.add(3); routeData.add("STI College");
        routeData.add("MI-04A"); routeData.add(4); routeData.add("Mandaue Coliseum");
        routeData.add("MI-04A"); routeData.add(5); routeData.add("Hotel Nenita");
        routeData.add("MI-04A"); routeData.add(6); routeData.add("University of Cebu");
        routeData.add("MI-04A"); routeData.add(7); routeData.add("Phoenix Publishing House");
        routeData.add("MI-04A"); routeData.add(8); routeData.add("Crown Regency Suites");
        routeData.add("MI-04A"); routeData.add(9); routeData.add("Pueblo Verde Terminal");
        routeData.add("MI-04A"); routeData.add(10); routeData.add("Tamiya Terminal");
        routeData.add("MI-04B"); routeData.add(1); routeData.add("Mepz1 2nd Ave Road");
        routeData.add("MI-04B"); routeData.add(2); routeData.add("Savemore");
        routeData.add("MI-04B"); routeData.add(3); routeData.add("Mactan Marina Mall");
        routeData.add("MI-04B"); routeData.add(4); routeData.add("The Bellavista Hotel");
        routeData.add("MI-04B"); routeData.add(5); routeData.add("Gaisano Macta");
        routeData.add("MI-04B"); routeData.add(6); routeData.add("PLDT");
        routeData.add("MI-04B"); routeData.add(7); routeData.add("Phoenix Publishing House");
        routeData.add("MI-04B"); routeData.add(8); routeData.add("Crown Regency Suites");
        routeData.add("MI-04B"); routeData.add(9); routeData.add("Robinsons Supermarket");
        routeData.add("MI-04B"); routeData.add(10); routeData.add("Tamiya Terminal");
        routeData.add("MI-05A"); routeData.add(1); routeData.add("Mactan Cebu International Airport");
        routeData.add("MI-05A"); routeData.add(2); routeData.add("Timex Philippines Incorporated");
        routeData.add("MI-05A"); routeData.add(3); routeData.add("Gaisano Mactan");
        routeData.add("MI-05A"); routeData.add(4); routeData.add("PLDT");
        routeData.add("MI-05A"); routeData.add(5); routeData.add("Lapu Lapu City PUJ Terminal");
        routeData.add("MI-05A"); routeData.add(6); routeData.add("Super Metro Gaisano Lapu Lapu");
        routeData.add("MI-05A"); routeData.add(7); routeData.add("Mantawe Road");
        routeData.add("MI-05A"); routeData.add(8); routeData.add("BM Dimataga St");
        routeData.add("MI-05A"); routeData.add(9); routeData.add("Opon Plaza");
        routeData.add("MI-05A"); routeData.add(10); routeData.add("Cebu Macta Ferry Terminal");


        return routeData;
    }
}
